apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: secrets-
spec:
  entrypoint: show-eos-dir
  volumes:
  - name: eos
    hostPath:
      path: /var/eos
  - name: krb-secret-vol
    secret:
      secretName: krb-secret
  templates:
  - name: show-eos-dir
    container:
      image: gitlab-registry.cern.ch/ai-ml/kubeflow_images/tensorflow-notebook-gpu-2.1.0:v0.6.1-30
      command: [sh, -c]
      args:
        - cp /secret/krb-secret-vol/krb5cc_1000 /tmp/krb5cc_1000;
          chmod 600 /tmp/krb5cc_1000;
          echo "EOS user directory files:";
          ls -l /eos/user/d/dgolubov;
      volumeMounts:
      - name: eos
        mountPath: /eos
      - name: krb-secret-vol
        mountPath: "/secret/krb-secret-vol"
