apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fairing-pvc
spec:
  storageClassName: geneva-cephfs-testing
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
